---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 20d773370efdfce3221f56348ba2c544558a58a3
    fabric8.io/git-branch: micro-config
    fabric8.io/git-url: https://github.com/thdoucet/DO288-apps.git
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: hello
    provider: fabric8
    version: "1.0"
    group: com.redhat.training.openshift
  name: hello
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
    provider: fabric8
    group: com.redhat.training.openshift
